-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Quality checks for contract cbs-cao-wages
-- Each statement returns a failure count; 0 = pass.

-- check: not_null(date,cao_sector_code)
SELECT count(*) FROM silver_cao_wages WHERE date IS NULL OR cao_sector_code IS NULL;

-- check: unique(date, cao_sector_code)
SELECT count(*) FROM (SELECT date, cao_sector_code FROM silver_cao_wages GROUP BY date, cao_sector_code HAVING count(*) > 1);

-- check: min_rows(300)
SELECT CASE WHEN count(*) >= 300 THEN 0 ELSE 1 END FROM silver_cao_wages;

-- check: range(wage_growth_yoy)
SELECT count(*) FROM silver_cao_wages WHERE wage_growth_yoy IS NOT NULL AND (wage_growth_yoy < -10 OR wage_growth_yoy > 20);

-- check: allowed_values(cao_sector_code)
SELECT count(*) FROM silver_cao_wages WHERE cao_sector_code IS NOT NULL AND cao_sector_code NOT IN ('T001020', '10610', '10620', '10601');

-- check: freshness(date<=92d)
SELECT CASE WHEN date_diff('day', max(date), current_date) <= 92 THEN 0 ELSE 1 END FROM silver_cao_wages;
