package carina.contracts.cbs_cao_wages

# GENERATED by `carina compile` — do not edit; edit the contract and recompile.
# contract: cbs-cao-wages  classification: public

import rego.v1

default allow := false

# The owning team may read and write.
allow if {
	input.resource.table == "silver_cao_wages"
	input.subject.groups[_] == "platform-team@carina.local"
	input.action in {"read", "write"}
}

# Public data: any authenticated principal may read.
allow if {
	input.action == "read"
	input.resource.table == "silver_cao_wages"
	input.subject.authenticated == true
}

# No column masks declared in this contract.
mask := set()
