-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Silver DDL for contract cbs-cao-wages
CREATE OR REPLACE TABLE silver_cao_wages AS SELECT 
    Periods AS period_code,
    substr(Periods, 5, 2) AS period_type,
    CAST(substr(Periods, 1, 4) AS INTEGER) AS year,
    CAST(substr(Periods, 7, 2) AS INTEGER) AS period_num,
    CASE substr(Periods, 5, 2)
        WHEN 'JJ' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), 1, 1)
        WHEN 'KW' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), (CAST(substr(Periods,7,2) AS INTEGER)-1)*3+1, 1)
        WHEN 'MM' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), CAST(substr(Periods,7,2) AS INTEGER), 1)
    END AS date
, CAST(trim(b.CaoSector) AS VARCHAR) AS cao_sector_code, CAST(trim(cao.Title) AS VARCHAR) AS cao_sector, CAST("MonthlyCaoWagesInclSpecialPayments_2" AS DOUBLE) AS wage_index_monthly, CAST("HourlyCaoWagesInclSpecialPayments_4" AS DOUBLE) AS wage_index_hourly, CAST("HourlyCaoWagesInclSpecialPayments_11" AS DOUBLE) AS wage_growth_yoy, CAST("HourlyContractualWageCosts_13" AS DOUBLE) AS wage_cost_growth_yoy FROM bronze_85663eng b LEFT JOIN bronze_85663eng__caosector AS cao ON trim(b."CaoSector") = trim(cao.Key) WHERE substr(Periods, 5, 2) = 'MM';
