-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Quality checks for contract cbs-labour-monthly
-- Each statement returns a failure count; 0 = pass.

-- check: not_null(date)
SELECT count(*) FROM silver_labour_monthly WHERE date IS NULL;

-- check: unique(date)
SELECT count(*) FROM (SELECT date FROM silver_labour_monthly GROUP BY date HAVING count(*) > 1);

-- check: min_rows(250)
SELECT CASE WHEN count(*) >= 250 THEN 0 ELSE 1 END FROM silver_labour_monthly;

-- check: range(unemployment_rate_sa)
SELECT count(*) FROM silver_labour_monthly WHERE unemployment_rate_sa IS NOT NULL AND (unemployment_rate_sa < 0 OR unemployment_rate_sa > 20);

-- check: range(net_participation_sa)
SELECT count(*) FROM silver_labour_monthly WHERE net_participation_sa IS NOT NULL AND (net_participation_sa < 40 OR net_participation_sa > 90);

-- check: freshness(date<=92d)
SELECT CASE WHEN date_diff('day', max(date), current_date) <= 92 THEN 0 ELSE 1 END FROM silver_labour_monthly;
