-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Silver DDL for contract cbs-labour-monthly
CREATE OR REPLACE TABLE silver_labour_monthly AS SELECT 
    Periods AS period_code,
    substr(Periods, 5, 2) AS period_type,
    CAST(substr(Periods, 1, 4) AS INTEGER) AS year,
    CAST(substr(Periods, 7, 2) AS INTEGER) AS period_num,
    CASE substr(Periods, 5, 2)
        WHEN 'JJ' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), 1, 1)
        WHEN 'KW' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), (CAST(substr(Periods,7,2) AS INTEGER)-1)*3+1, 1)
        WHEN 'MM' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), CAST(substr(Periods,7,2) AS INTEGER), 1)
    END AS date
, CAST("SeasonallyAdjusted_2" AS DOUBLE) AS labour_force_sa, CAST("SeasonallyAdjusted_4" AS DOUBLE) AS employed_sa, CAST("SeasonallyAdjusted_6" AS DOUBLE) AS unemployed_sa, CAST("SeasonallyAdjusted_8" AS DOUBLE) AS unemployment_rate_sa, CAST("SeasonallyAdjusted_12" AS DOUBLE) AS gross_participation_sa, CAST("SeasonallyAdjusted_14" AS DOUBLE) AS net_participation_sa FROM bronze_80590eng b WHERE substr(Periods, 5, 2) = 'MM';
