-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Quality checks for contract cbs-vacancies-sector
-- Each statement returns a failure count; 0 = pass.

-- check: not_null(date,sector_code)
SELECT count(*) FROM silver_vacancies_sector WHERE date IS NULL OR sector_code IS NULL;

-- check: unique(date, sector_code)
SELECT count(*) FROM (SELECT date, sector_code FROM silver_vacancies_sector GROUP BY date, sector_code HAVING count(*) > 1);

-- check: min_rows(5000)
SELECT CASE WHEN count(*) >= 5000 THEN 0 ELSE 1 END FROM silver_vacancies_sector;

-- check: range(vacancies_unfilled)
SELECT count(*) FROM silver_vacancies_sector WHERE vacancies_unfilled IS NOT NULL AND (vacancies_unfilled < 0 OR vacancies_unfilled > 600);

-- check: freshness(date<=200d)
SELECT CASE WHEN date_diff('day', max(date), current_date) <= 200 THEN 0 ELSE 1 END FROM silver_vacancies_sector;
