-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Silver DDL for contract cbs-vacancies-sector
CREATE OR REPLACE TABLE silver_vacancies_sector AS SELECT 
    Periods AS period_code,
    substr(Periods, 5, 2) AS period_type,
    CAST(substr(Periods, 1, 4) AS INTEGER) AS year,
    CAST(substr(Periods, 7, 2) AS INTEGER) AS period_num,
    CASE substr(Periods, 5, 2)
        WHEN 'JJ' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), 1, 1)
        WHEN 'KW' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), (CAST(substr(Periods,7,2) AS INTEGER)-1)*3+1, 1)
        WHEN 'MM' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), CAST(substr(Periods,7,2) AS INTEGER), 1)
    END AS date
, CAST(trim(b.SIC2008SizeClasses) AS VARCHAR) AS sector_code, CAST(trim(sic.Title) AS VARCHAR) AS sector, CAST("UnfilledVacancies_1" AS DOUBLE) AS vacancies_unfilled, CAST("NewVacancies_2" AS DOUBLE) AS vacancies_new, CAST("FilledVacancies_3" AS DOUBLE) AS vacancies_filled FROM bronze_80472eng b LEFT JOIN bronze_80472eng__sic2008sizeclasses AS sic ON trim(b."SIC2008SizeClasses") = trim(sic.Key) WHERE substr(Periods, 5, 2) = 'KW';
