-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Quality checks for contract cbs-participation-keyfigures
-- Each statement returns a failure count; 0 = pass.

-- check: not_null(date,age_code)
SELECT count(*) FROM silver_participation WHERE date IS NULL OR age_code IS NULL;

-- check: unique(date, age_code, period_type)
SELECT count(*) FROM (SELECT date, age_code, period_type FROM silver_participation GROUP BY date, age_code, period_type HAVING count(*) > 1);

-- check: min_rows(1200)
SELECT CASE WHEN count(*) >= 1200 THEN 0 ELSE 1 END FROM silver_participation;

-- check: range(net_participation)
SELECT count(*) FROM silver_participation WHERE net_participation IS NOT NULL AND (net_participation < 0 OR net_participation > 100);

-- check: freshness(date<=200d)
SELECT CASE WHEN date_diff('day', max(date), current_date) <= 200 THEN 0 ELSE 1 END FROM silver_participation;
