-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Silver DDL for contract cbs-participation-keyfigures
CREATE OR REPLACE TABLE silver_participation AS SELECT 
    Periods AS period_code,
    substr(Periods, 5, 2) AS period_type,
    CAST(substr(Periods, 1, 4) AS INTEGER) AS year,
    CAST(substr(Periods, 7, 2) AS INTEGER) AS period_num,
    CASE substr(Periods, 5, 2)
        WHEN 'JJ' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), 1, 1)
        WHEN 'KW' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), (CAST(substr(Periods,7,2) AS INTEGER)-1)*3+1, 1)
        WHEN 'MM' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), CAST(substr(Periods,7,2) AS INTEGER), 1)
    END AS date
, CAST(trim(b.Age) AS VARCHAR) AS age_code, CAST(trim(age.Title) AS VARCHAR) AS age_group, CAST("EmployedLabourForce_3" AS DOUBLE) AS employed, CAST("PermanentEmployee_5" AS DOUBLE) AS permanent_employee, CAST("FlexibleEmployee_6" AS DOUBLE) AS flexible_employee, CAST("SelfEmployedPerson_7" AS DOUBLE) AS self_employed, CAST("PartTime_12" AS DOUBLE) AS part_time, CAST("FullTime_19" AS DOUBLE) AS full_time, CAST("UnemploymentRate_21" AS DOUBLE) AS unemployment_rate, CAST("NetLabourParticipationRate_24" AS DOUBLE) AS net_participation FROM bronze_85264eng b LEFT JOIN bronze_85264eng__age AS age ON trim(b."Age") = trim(age.Key) WHERE 1=1;
