"""Contract compiler v1 (Phase 1 — KEEL, ADR-0011).

One ODCS-flavored contract compiles into every enforcement artifact the
platform needs. Handwriting any of these is a bug:

  silver.sql    — the silver DDL the ingest runs (the *same* SQL, one source)
  checks.sql    — the quality checks as executable SQL
  policy.rego   — the OPA policy (access rules + column masks)
  catalog.json  — the catalog entry (Iceberg-REST / Lakekeeper shaped)
  fga-tuples.json — OpenFGA relationship tuples for the product + contracts

`carina compile` writes them under products/<product>/compiled/ so drift is
visible in code review; `carina compile --check` is the CI gate that fails
when a contract changed but its compiled artifacts did not.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from . import config
from .contracts import Contract, Product

# Built-in period parsing: CBS period codes look like 2003JJ00 (year),
# 1997KW01 (quarter), 2026MM05 (month). Every silver table carries these.
PERIOD_SQL = """
    {periods_col} AS period_code,
    substr({periods_col}, 5, 2) AS period_type,
    CAST(substr({periods_col}, 1, 4) AS INTEGER) AS year,
    CAST(substr({periods_col}, 7, 2) AS INTEGER) AS period_num,
    CASE substr({periods_col}, 5, 2)
        WHEN 'JJ' THEN make_date(CAST(substr({periods_col},1,4) AS INTEGER), 1, 1)
        WHEN 'KW' THEN make_date(CAST(substr({periods_col},1,4) AS INTEGER), (CAST(substr({periods_col},7,2) AS INTEGER)-1)*3+1, 1)
        WHEN 'MM' THEN make_date(CAST(substr({periods_col},1,4) AS INTEGER), CAST(substr({periods_col},7,2) AS INTEGER), 1)
    END AS date
"""

PERIOD_COLUMNS = [
    {"name": "period_code", "type": "VARCHAR", "description": "Raw source period code"},
    {"name": "period_type", "type": "VARCHAR", "description": "JJ=year, KW=quarter, MM=month"},
    {"name": "year", "type": "INTEGER", "description": "Calendar year"},
    {"name": "period_num", "type": "INTEGER", "description": "Month or quarter number within the year"},
    {"name": "date", "type": "DATE", "description": "Period start date"},
]

GENERATED_HEADER = "GENERATED by `carina compile` — do not edit; edit the contract and recompile."


def bronze_table(contract: Contract) -> str:
    return f"bronze_{contract.source['table'].lower()}"


# ---- silver DDL -------------------------------------------------------------

def compile_silver_sql(contract: Contract) -> str:
    """The exact DDL ingest runs to build the silver table from bronze."""
    silver = contract.silver
    cols_sql = [PERIOD_SQL.format(periods_col=silver.get("periods_column", "Periods"))]
    for col in silver.get("columns", []):
        expr = f'"{col["from"]}"' if "from" in col else col["expr"]
        cols_sql.append(f'CAST({expr} AS {col.get("type", "VARCHAR")}) AS {col["name"]}')

    joins = ""
    table_id = contract.source["table"]
    for j in silver.get("dim_joins", []):
        dim_table = f"bronze_{table_id.lower()}__{j['dimension'].lower()}"
        joins += (
            f' LEFT JOIN {dim_table} AS {j["alias"]} '
            f'ON trim(b."{j["dimension"]}") = trim({j["alias"]}.Key)'
        )

    where = silver.get("where", "1=1")
    return (
        f"CREATE OR REPLACE TABLE {contract.silver_table} AS "
        f"SELECT {', '.join(cols_sql)} FROM {bronze_table(contract)} b{joins} WHERE {where}"
    )


# ---- quality checks ---------------------------------------------------------

def compile_check(check: dict, table: str) -> tuple[str, str]:
    """Compile one contract check into (name, sql). SQL returns failure count."""
    t = check["type"]
    if t == "not_null":
        cols = check["columns"]
        cond = " OR ".join(f"{c} IS NULL" for c in cols)
        return f"not_null({','.join(cols)})", f"SELECT count(*) FROM {table} WHERE {cond}"
    if t == "unique":
        cols = ", ".join(check["columns"])
        return (
            f"unique({cols})",
            f"SELECT count(*) FROM (SELECT {cols} FROM {table} GROUP BY {cols} HAVING count(*) > 1)",
        )
    if t == "range":
        c, lo, hi = check["column"], check.get("min"), check.get("max")
        conds = []
        if lo is not None:
            conds.append(f"{c} < {lo}")
        if hi is not None:
            conds.append(f"{c} > {hi}")
        return (
            f"range({c})",
            f"SELECT count(*) FROM {table} WHERE {c} IS NOT NULL AND ({' OR '.join(conds)})",
        )
    if t == "min_rows":
        n = check["value"]
        return f"min_rows({n})", f"SELECT CASE WHEN count(*) >= {n} THEN 0 ELSE 1 END FROM {table}"
    if t == "freshness":
        c, days = check.get("column", "date"), check["max_lag_days"]
        return (
            f"freshness({c}<={days}d)",
            f"SELECT CASE WHEN date_diff('day', max({c}), current_date) <= {days} THEN 0 ELSE 1 END FROM {table}",
        )
    if t == "allowed_values":
        c = check["column"]
        vals = ", ".join(f"'{v}'" for v in check["values"])
        return (
            f"allowed_values({c})",
            f"SELECT count(*) FROM {table} WHERE {c} IS NOT NULL AND {c} NOT IN ({vals})",
        )
    if t == "nonempty":
        return f"nonempty({table})", f"SELECT CASE WHEN count(*) > 0 THEN 0 ELSE 1 END FROM {table}"
    raise ValueError(f"Unknown check type: {t}")


def compile_checks_sql(contract: Contract) -> str:
    parts = [f"-- {GENERATED_HEADER}", f"-- Quality checks for contract {contract.id}",
             "-- Each statement returns a failure count; 0 = pass.", ""]
    for check in contract.checks:
        name, sql = compile_check(check, contract.silver_table)
        parts.append(f"-- check: {name}")
        parts.append(sql + ";")
        parts.append("")
    return "\n".join(parts)


# ---- OPA policy -------------------------------------------------------------

def _rego_package(contract_id: str) -> str:
    return "carina.contracts." + contract_id.replace("-", "_")


def compile_policy_rego(contract: Contract) -> str:
    """Generated Rego: who may read/write this contract's table, and which
    columns are masked. The production OPA sidecar loads exactly this file;
    the laptop profile ships it as a compiled artifact (ADR-0009)."""
    access = contract.raw.get("access", {})
    consumers = access.get("consumers", [])
    masks = access.get("masks", [])
    table = contract.silver_table

    lines = [
        f"package {_rego_package(contract.id)}",
        "",
        f"# {GENERATED_HEADER}",
        f"# contract: {contract.id}  classification: {contract.classification}",
        "",
        "import rego.v1",
        "",
        "default allow := false",
        "",
        "# The owning team may read and write.",
        "allow if {",
        f'\tinput.resource.table == "{table}"',
        f'\tinput.subject.groups[_] == "{contract.owner}"',
        '\tinput.action in {"read", "write"}',
        "}",
        "",
    ]
    if contract.classification == "public":
        lines += [
            "# Public data: any authenticated principal may read.",
            "allow if {",
            '\tinput.action == "read"',
            f'\tinput.resource.table == "{table}"',
            "\tinput.subject.authenticated == true",
            "}",
            "",
        ]
    for group in consumers:
        lines += [
            f"# Contract-declared consumer: {group}",
            "allow if {",
            '\tinput.action == "read"',
            f'\tinput.resource.table == "{table}"',
            f'\tinput.subject.groups[_] == "{group}"',
            "}",
            "",
        ]
    if masks:
        lines += [
            "owner_member if {",
            f'\tinput.subject.groups[_] == "{contract.owner}"',
            "}",
            "",
            "# Columns masked unless the subject owns the contract.",
        ]
        for m in masks:
            lines += [
                "mask contains col if {",
                f'\tcol := {{"column": "{m["column"]}", "treatment": "{m.get("treatment", "null")}"}}',
                "\tnot owner_member",
                "}",
                "",
            ]
    else:
        lines += ["# No column masks declared in this contract.", "mask := set()", ""]
    return "\n".join(lines)


# ---- catalog entry ----------------------------------------------------------

_ICEBERG_TYPES = {
    "DOUBLE": "double", "FLOAT": "float", "REAL": "float",
    "INTEGER": "int", "INT": "int", "BIGINT": "long", "SMALLINT": "int",
    "VARCHAR": "string", "TEXT": "string",
    "DATE": "date", "TIMESTAMP": "timestamp", "BOOLEAN": "boolean",
}


def compile_catalog_entry(contract: Contract) -> dict:
    """Iceberg-REST-shaped table metadata — what `carina compile` would POST
    to Lakekeeper when the catalog lane attaches."""
    ns_product = contract.product_id.replace("-", "_")
    fields = []
    all_cols = PERIOD_COLUMNS + contract.silver.get("columns", [])
    for i, col in enumerate(all_cols, start=1):
        doc = col.get("description", "")
        if col.get("unit"):
            doc = f"{doc} [{col['unit']}]" if doc else f"[{col['unit']}]"
        fields.append({
            "id": i,
            "name": col["name"],
            "type": _ICEBERG_TYPES.get(col.get("type", "VARCHAR").upper(), "string"),
            "required": False,
            **({"doc": doc} if doc else {}),
        })
    src = contract.source
    props = {
        "carina.contract": contract.id,
        "carina.owner": contract.owner,
        "carina.classification": contract.classification,
        "carina.product": contract.product_id,
    }
    for key, value in [
        ("source.system", src.get("type")),
        ("source.table", src.get("table")),
        ("source.url", src.get("landing_page") or src.get("url")),
        ("source.license", src.get("license")),
        ("source.attribution", src.get("attribution")),
        ("refresh.cadence", contract.raw.get("refresh", {}).get("cadence")),
        ("refresh.sla", contract.raw.get("refresh", {}).get("sla")),
    ]:
        if value:
            props[key] = value
    return {
        "_generated": GENERATED_HEADER,
        "namespace": ["carina", ns_product, "silver"],
        "name": contract.silver_table,
        "schema": {"type": "struct", "fields": fields},
        "properties": props,
    }


# ---- OpenFGA tuples ---------------------------------------------------------

FGA_MODEL = {
    "schema_version": "1.1",
    "type_definitions": [
        {"type": "user"},
        {"type": "group", "relations": {"member": {"this": {}}}},
        {
            "type": "contract",
            "relations": {"owner": {"this": {}}, "reader": {"this": {}}},
        },
        {
            "type": "product",
            "relations": {"owner": {"this": {}}, "reader": {"this": {}}, "source": {"this": {}}},
        },
    ],
}


def compile_fga_tuples(product: Product) -> dict:
    """OpenFGA relationship tuples: ownership and read grants for the product
    and each contract, derived from contract fields — never hand-managed."""
    tuples = [
        {"user": f"group:{product.raw.get('owner', 'unknown')}", "relation": "owner",
         "object": f"product:{product.id}"},
    ]
    for ct in product.contracts:
        tuples.append({"user": f"group:{ct.owner}", "relation": "owner",
                       "object": f"contract:{ct.id}"})
        tuples.append({"user": f"contract:{ct.id}", "relation": "source",
                       "object": f"product:{product.id}"})
        if ct.classification == "public":
            tuples.append({"user": "user:*", "relation": "reader",
                           "object": f"contract:{ct.id}"})
        for group in ct.raw.get("access", {}).get("consumers", []):
            tuples.append({"user": f"group:{group}", "relation": "reader",
                           "object": f"contract:{ct.id}"})
    return {"_generated": GENERATED_HEADER, "authorization_model": FGA_MODEL, "tuples": tuples}


# ---- artifact assembly ------------------------------------------------------

def compile_product(product: Product) -> dict[str, str]:
    """All compiled artifacts for a product, as {relative_path: content}."""
    artifacts: dict[str, str] = {}
    for ct in product.contracts:
        base = ct.id
        artifacts[f"{base}/silver.sql"] = (
            f"-- {GENERATED_HEADER}\n-- Silver DDL for contract {ct.id}\n"
            + compile_silver_sql(ct) + ";\n"
        )
        artifacts[f"{base}/checks.sql"] = compile_checks_sql(ct)
        artifacts[f"{base}/policy.rego"] = compile_policy_rego(ct)
        artifacts[f"{base}/catalog.json"] = json.dumps(
            compile_catalog_entry(ct), indent=2, sort_keys=True) + "\n"
    artifacts["fga-tuples.json"] = json.dumps(
        compile_fga_tuples(product), indent=2, sort_keys=True) + "\n"
    return artifacts


def compiled_dir(product: Product) -> Path:
    return product.path / "compiled"


def write_artifacts(product: Product) -> dict:
    """Write compiled artifacts to disk; returns {written, changed, unchanged}."""
    artifacts = compile_product(product)
    out = compiled_dir(product)
    changed, unchanged = [], []
    for rel, content in artifacts.items():
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_text() == content:
            unchanged.append(rel)
        else:
            path.write_text(content)
            changed.append(rel)
    # Remove stale artifacts (e.g. a contract was deleted or renamed).
    removed = []
    for existing in sorted(out.rglob("*")):
        if existing.is_file() and str(existing.relative_to(out)) not in artifacts:
            existing.unlink()
            removed.append(str(existing.relative_to(out)))
    digest = hashlib.sha256(
        "".join(f"{k}\x00{v}\x01" for k, v in sorted(artifacts.items())).encode()
    ).hexdigest()
    return {"product": product.id, "artifacts": sorted(artifacts),
            "changed": sorted(changed), "unchanged": sorted(unchanged),
            "removed": removed, "digest": digest}


def compile_policy_bundle(products: list[Product]) -> dict[str, str]:
    """The OPA bundle tree (implementation-plan layout: policies/): every
    generated Rego policy plus the kustomization that ships them to the
    in-cluster OPA as one ConfigMap. Git → Argo CD → OPA; no other path."""
    artifacts: dict[str, str] = {}
    rego_paths = []
    for product in products:
        for ct in product.contracts:
            rel = f"generated/{product.id}/{ct.id}.rego"
            artifacts[rel] = compile_policy_rego(ct)
            rego_paths.append(rel)
    files = "\n".join(f"      - {p}" for p in sorted(rego_paths))
    artifacts["kustomization.yaml"] = (
        f"# {GENERATED_HEADER}\n"
        "# Ships every generated contract policy to the trust-plane OPA as one\n"
        "# ConfigMap (see platform/planes/trust-plane/opa/).\n"
        "apiVersion: kustomize.config.k8s.io/v1beta1\n"
        "kind: Kustomization\n"
        "namespace: trust-plane\n"
        "generatorOptions:\n"
        "  disableNameSuffixHash: true\n"
        "configMapGenerator:\n"
        "  - name: opa-policies\n"
        "    files:\n"
        f"{files}\n"
    )
    return artifacts


def policies_dir() -> Path:
    return config.ROOT / "policies"


def write_policy_bundle(products: list[Product]) -> dict:
    artifacts = compile_policy_bundle(products)
    out = policies_dir()
    changed = []
    for rel, content in artifacts.items():
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
            changed.append(rel)
    removed = []
    gen = out / "generated"
    if gen.exists():
        for existing in sorted(gen.rglob("*.rego")):
            rel = str(existing.relative_to(out))
            if rel not in artifacts:
                existing.unlink()
                removed.append(rel)
    return {"artifacts": sorted(artifacts), "changed": changed, "removed": removed}


def check_policy_bundle(products: list[Product]) -> list[str]:
    artifacts = compile_policy_bundle(products)
    out = policies_dir()
    stale = [
        rel for rel, content in artifacts.items()
        if not (out / rel).exists() or (out / rel).read_text() != content
    ]
    gen = out / "generated"
    if gen.exists():
        for existing in sorted(gen.rglob("*.rego")):
            rel = str(existing.relative_to(out))
            if rel not in artifacts:
                stale.append(rel + " (orphaned)")
    return stale


def check_artifacts(product: Product) -> list[str]:
    """CI gate: return artifact paths whose on-disk content is stale/missing."""
    artifacts = compile_product(product)
    out = compiled_dir(product)
    stale = [
        rel for rel, content in artifacts.items()
        if not (out / rel).exists() or (out / rel).read_text() != content
    ]
    for existing in sorted(out.rglob("*")) if out.exists() else []:
        if existing.is_file() and str(existing.relative_to(out)) not in artifacts:
            stale.append(str(existing.relative_to(out)) + " (orphaned)")
    return stale
