-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Quality checks for contract cbs-employment-sector
-- Each statement returns a failure count; 0 = pass.

-- check: not_null(date,sector_code)
SELECT count(*) FROM silver_employment_sector WHERE date IS NULL OR sector_code IS NULL;

-- check: unique(date, sector_code)
SELECT count(*) FROM (SELECT date, sector_code FROM silver_employment_sector GROUP BY date, sector_code HAVING count(*) > 1);

-- check: min_rows(1500)
SELECT CASE WHEN count(*) >= 1500 THEN 0 ELSE 1 END FROM silver_employment_sector;

-- check: range(employed_persons_sa)
SELECT count(*) FROM silver_employment_sector WHERE employed_persons_sa IS NOT NULL AND (employed_persons_sa < 0 OR employed_persons_sa > 15000);

-- check: freshness(date<=200d)
SELECT CASE WHEN date_diff('day', max(date), current_date) <= 200 THEN 0 ELSE 1 END FROM silver_employment_sector;
