-- GENERATED by `carina compile` — do not edit; edit the contract and recompile.
-- Silver DDL for contract cbs-employment-sector
CREATE OR REPLACE TABLE silver_employment_sector AS SELECT 
    Periods AS period_code,
    substr(Periods, 5, 2) AS period_type,
    CAST(substr(Periods, 1, 4) AS INTEGER) AS year,
    CAST(substr(Periods, 7, 2) AS INTEGER) AS period_num,
    CASE substr(Periods, 5, 2)
        WHEN 'JJ' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), 1, 1)
        WHEN 'KW' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), (CAST(substr(Periods,7,2) AS INTEGER)-1)*3+1, 1)
        WHEN 'MM' THEN make_date(CAST(substr(Periods,1,4) AS INTEGER), CAST(substr(Periods,7,2) AS INTEGER), 1)
    END AS date
, CAST(trim(b.SectorBranchesSIC2008) AS VARCHAR) AS sector_code, CAST(trim(sec.Title) AS VARCHAR) AS sector, CAST("EmployedPersonsSeasonalAdjusted_2" AS DOUBLE) AS employed_persons_sa, CAST("JobsSeasonalAdjusted_4" AS DOUBLE) AS jobs_sa, CAST("HoursWorked_5" AS DOUBLE) AS hours_worked FROM bronze_85920eng b LEFT JOIN bronze_85920eng__sectorbranchessic2008 AS sec ON trim(b."SectorBranchesSIC2008") = trim(sec.Key) WHERE substr(Periods, 5, 2) = 'KW';
